services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest

  api:
    image: ${DOCKER_REGISTRY-}hospital-api
    build:
      context: ./src/API
      dockerfile: Dockerfile

  client:
    image: ${DOCKER_REGISTRY-}hospital-client
    build:
      context: ./src/Client
      dockerfile: Dockerfile