services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest

  api:
    image: ${DOCKER_REGISTRY-}hospital-api
    build:
      context: .
      dockerfile: src/API/Dockerfile

  client:
    image: ${DOCKER_REGISTRY-}hospital-client
    build:
      context: .
      dockerfile: src/Client/Dockerfile